module.exports = {
  CONNECT: 'EVENT_CONNECT',
  COMMAND: 'EVENT_COMMAND',
  GET_CONNECT_CONFIG: 'EVENT_GET_CONNECT_CONFIG',
  ADD_CONNECT_CONFIG: 'EVENT_ADD_CONNECT_CONFIG',
  DEL_CONNECT_CONFIG: 'EVENT_DEL_CONNECT_CONFIG',
}
